platform :ios, '8.0'
use_frameworks!

target 'MarsTimeConversion_Example' do
  pod 'MarsTimeConversion', :path => '../'

  target 'MarsTimeConversion_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.1'
    pod 'Nimble', '~> 6.1'
  end
end
