platform :ios, '8.0'
use_frameworks!

target 'MarsTimeConversion_Example' do
  pod 'MarsTimeConversion', :path => '../'

  target 'MarsTimeConversion_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
