use_frameworks!

target 'MarsTimeConversion_Example' do
  pod 'MarsTimeConversion', :path => '../'

  target 'MarsTimeConversion_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
